---
- name: launch compute instance
  hosts: common 
  tasks:
  #  - name: Check if instance already exists
  #    command: nova show "{{item.name}}"
  #    with_items: instance_detail
  #    ignore_errors: true
  #    register: check_instance
 
   # - debug: var=check_instance
   #   when: check_instance.failed


    #- debug: msg="failed"
    #  when: check_instance.rc == 0
    #- debug: var=check_instance.rc


   #- name: debug
   #  os_server_facts:
     # server: "{{item.name}}"
     #with_items: instance_detail
   #  register: server_status

   #- debug: msg="{{ openstack_servers }}"

  # - debug:
  #    var: server_status
  # - debug:
      #var: addresses 
   #   var: "{{ server_status.ansible_facts.openstack_servers.az }}" 
    # when: server_status.OS-EXT-STS:vm_state == "active"
